service: express-ts-lambda

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-offline
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

functions:
  app:
    handler: "src/server.handler"
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"
  tscpaths:
    buildPath: .build
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: ${env:PORT}
    host: ${env:HOST}
